"use strict";
// DO NOT EDIT THIS FILE, EDIT THE GRUNT TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
angular.module("refset")

.constant("ENV", {
	"name": "development",
	"apiEndpoint": "http://dev-refset.ihtsdotools.org:8080/refset"
})

;